version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: nestjs
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: nestjsss
    volumes:
      - pgdata:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=nestjs
      - RABBITMQ_DEFAULT_PASS=nestjs
volumes:
  pgdata:
