version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: nestjs
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: nestjsss
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
